name: production

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest]
        node-version: [22.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4

      - name: 🛠️ Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: 📥 Download and clean install dependencies
        env:
          HUSKY: 0
        run: npm ci

      - name: 🧪 Run tests
        env: 
          APP_API_SUBDOMAIN: ${{ vars.APP_API_SUBDOMAIN }}
          APP_DOMAIN: ${{ vars.APP_DOMAIN }}
          TELEGRAF_WEBHOOK_DOMAIN: ${{ vars.TELEGRAF_WEBHOOK_DOMAIN }}
          ILOVEAPI_PUBLIC_KEY: ${{ secrets.ILOVEAPI_PUBLIC_KEY }}
          ILOVEAPI_SECRET_KEY: ${{ secrets.ILOVEAPI_SECRET_KEY }}
          TELEGRAF_BOT_TOKEN: ${{ secrets.TELEGRAF_BOT_TOKEN }}
          TELEGRAF_WEBHOOK_SECRET_TOKEN: ${{ secrets.TELEGRAF_WEBHOOK_SECRET_TOKEN }}
        run: npm run test
